version: "3.7"     

services:
  web:     
    build: .                               
    command: python manage.py runserver 0.0.0.0:8000
    ports:              
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - WARMDATA_DB_HOST=postgres
      - WARMDATA_DB_PORT=5432
      - WARMDATA_DB_NAME=postgres
      - WARMDATA_DB_USERNAME=postgres
      - WARMDATA_DB_USERNAME_WARM=warm
      - WARMDATA_DB_PASSWORD=postgres
  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
